apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: genesis-ns
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_URL: "jdbc:postgresql://db.ybggislwzccxquzhqjmt.supabase.co:5432/postgres?sslmode=require"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  CLIENT_URL: "http://localhost:5173"
  MINIO_URL: "https://ead38d510292f1d0c211505e945022c3.r2.cloudflarestorage.com"
  MINIO_BUCKET: "lovable"
