apiVersion: apps/v1
kind: Deployment
metadata:
  name: genesis-proxy
  namespace: genesis-ns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: genesis-proxy
  template:
    metadata:
      labels:
        app: genesis-proxy
    spec:
      containers:
        - name: proxy
          image: sydv3604/genesis-proxy:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "5m"
              memory: "16Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          env:
            - name: REDIS_URL
              # Refers to the service in the same namespace
              value: "redis://redis-service:6379"
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: genesis-proxy-svc
  namespace: genesis-ns
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: genesis-proxy