apiVersion: v1
kind: Namespace
metadata:
  name: genesis-ns

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: minio-service
#   namespace: genesis-ns
# spec:
#   type: ExternalName
#   externalName: host.docker.internal # Points to your laptop/host
#   ports:
#     - port: 9000
#       targetPort: 9000
#       protocol: TCP

# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: genesis-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: genesis-ns
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
