apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-pool
  namespace: genesis-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: runner
      status: idle #will be changed to running
  template:
    metadata:
      labels:
        app: runner
        status: idle
    spec:
      volumes:
        - name: workspace
          emptyDir: {}
        - name: pnpm-store
          hostPath:
            path: /mnt/pnpm-store
            type: DirectoryOrCreate
      containers:
        - name: runner
          image: node:20-alpine
          workingDir: /app
          command: ["/bin/sh", "-c", "sleep infinity"]
          volumeMounts:
            - name: workspace
              mountPath: /app
            - name: pnpm-store
              mountPath: /root/.local/share/pnpm
          ports:
            - containerPort: 5173
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

        # 2. THE SYNCER (File Sync)
        - name: syncer
          image: minio/mc
          command: ["/bin/sh", "-c", "sleep infinity"]
          env:
            - name: R2_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MINIO_ACCESS_KEY
            - name: R2_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MINIO_SECRET_KEY
            - name: MC_HOST_cloudflareR2
              value: "https://$(R2_ACCESS_KEY_ID):$(R2_SECRET_ACCESS_KEY)@ead38d510292f1d0c211505e945022c3.r2.cloudflarestorage.com"
          volumeMounts:
            - name: workspace
              mountPath: /app
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "50m"
